// ─────────────────────────────────────────────────────────────
// EL PLAN DE JUAN. Todo lo que se puede editar está aquí.
// Después de cambiar este archivo, sube VERSION en sw.js.
// ─────────────────────────────────────────────────────────────

// Valores por defecto de la configuración inicial
export const DEFAULTS = {
  nombre: 'Juan',
  inicio: '2026-10-05',
  gym: ['lun', 'mie', 'vie'],              // en orden: A, B, C
  agua: ['lun', 'mar', 'mie', 'jue', 'vie'],
  pieplano: true,
  ligero: true,
  tema: 'auto',
  comp: { nombre: 'Juegos Deportivos Nacionales', corto: 'los Juegos Nacionales', ini: '2026-11-15', fin: '', lugar: '', piscina: 50 },
};

// ── Transferencia al agua ────────────────────────────────────
export const TRANSFER = {
  salida:     { n: 'Salida',          c: 'var(--aqua)', i: '<path d="M3 20h8v-5"/><path d="M11 15L20 6"/><path d="M14 6h6v6"/>' },
  viraje:     { n: 'Viraje',          c: 'var(--cielo)', i: '<path d="M20 3v18"/><path d="M16 7H9a5 5 0 0 0 0 10h7"/><path d="M13 14l3 3-3 3"/>' },
  patada:     { n: 'Patada de pecho', c: 'var(--turq)', i: '<path d="M5 4c0 6 3 9 7 9s7-3 7-9"/><path d="M4 20c3-3 5-4 8-4s5 1 8 4"/>' },
  brazada:    { n: 'Brazada de pecho', c: 'var(--azul)', i: '<path d="M12 4v7"/><path d="M12 11c-4 0-7 2-8 5M12 11c4 0 7 2 8 5"/><path d="M4 16c2 3 5 4 8 4s6-1 8-4"/>' },
  sprint:     { n: 'Sprint libre',    c: 'var(--amarillo)', i: '<path d="M13 2L4 14h7l-1 8 9-12h-7z"/>' },
  streamline: { n: 'Streamline',      c: 'var(--celeste)', i: '<path d="M2 12h16"/><path d="M14 7l6 5-6 5"/><path d="M2 18c2 0 2-1.5 4-1.5S8 18 10 18"/>' },
  hombro:     { n: 'Hombro sano',     c: 'var(--salmon)', i: '<path d="M12 3l7 3v5c0 5-3 8-7 10-4-2-7-5-7-10V6z"/><path d="M9 12l2 2 4-4"/>' },
  rodilla:    { n: 'Rodilla sana',    c: 'var(--salmon)', i: '<path d="M12 3l7 3v5c0 5-3 8-7 10-4-2-7-5-7-10V6z"/><path d="M12 9v6M9 12h6"/>' },
};

// ── Mapa del cuerpo: zona → color ────────────────────────────
export const GRUPOS = {
  piernas:   { n: 'Piernas',        c: 'var(--turq)' },
  posterior: { n: 'Glúteo/femoral', c: 'var(--aqua)' },
  espalda:   { n: 'Espalda',        c: 'var(--azul)' },
  hombros:   { n: 'Hombros',        c: 'var(--salmon)' },
  brazos:    { n: 'Brazos',         c: 'var(--lila)' },
  pecho:     { n: 'Pecho',          c: 'var(--coral)' },
  core:      { n: 'Core',           c: 'var(--amarillo)' },
};
export const ZONAS = {
  cuadriceps: 'piernas', aductor: 'piernas', pantorrilla: 'piernas',
  gluteo: 'posterior', gluteoMedio: 'posterior', femoral: 'posterior',
  dorsal: 'espalda', trapecio: 'espalda', lumbar: 'espalda',
  deltoides: 'hombros', deltoidesPost: 'hombros',
  biceps: 'brazos', triceps: 'brazos', antebrazo: 'brazos',
  pecho: 'pecho', abdomen: 'core', oblicuos: 'core',
};

// ── Pesos guiados (nadador de 16 años, 55-65 kg, sin experiencia) ──
// eq: manc (una mancuerna) · mano (una en cada mano) · barra · maquina · balon · banda · cajon · corporal
// ini / tope: [kg, lb]; se usa el de la unidad del equipo (barras en lb, el resto en kg). ini 0 = peso corporal.
// barra: 'z' (barra Z), 'oli' (olímpica) o 'smith'; topeExtra = discos sobre la barra.
export const PESOS = {
  goblet:      { eq: 'manc', ini: [8, 17.5], tope: [20, 45] },
  sentBarra:   { eq: 'barra', barra: 'z', ini: 'barra', tope: [35, 75], nota: 'Empieza con la barra Z o la barra sola.' },
  smith:       { eq: 'barra', barra: 'smith', ini: 'barra', tope: [35, 75], nota: 'Empieza con la barra sola de la máquina.' },
  sumo:        { eq: 'manc', ini: [8, 17.5], tope: [20, 45] },
  puente1:     { eq: 'manc', ini: 0, tope: [8, 17.5], desde: 3, nota: 'Mancuerna sobre la cadera, solo desde la semana 3.' },
  hipthrust:   { eq: 'manc', ini: [10, 20], tope: [25, 55] },
  rdl:         { eq: 'mano', ini: [6, 12.5], tope: [16, 35] },
  bulgara:     { eq: 'mano', ini: [4, 10], tope: [10, 22.5], sinPesoSem1: true, nota: 'La semana 1 va sin peso.' },
  zancada:     { eq: 'mano', ini: 0, tope: [8, 17.5] },
  stepup:      { eq: 'mano', ini: 0, tope: [8, 17.5] },
  pressMil:    { eq: 'mano', ini: [4, 10], tope: [10, 22.5] },
  landmine:    { eq: 'barra', barra: 'oli', ini: 'barra', topeExtra: [10, 20], nota: 'Empieza con la barra sola.' },
  pullover:    { eq: 'manc', ini: [6, 12.5], tope: [12, 25] },
  pulloverPolea: { eq: 'maquina', ini: [5, 10], tope: [12.5, 25] },
  remoMano:    { eq: 'manc', ini: [8, 17.5], tope: [18, 40] },
  jalon:       { eq: 'maquina', ini: [25, 55], tope: [45, 100] },
  remoPolea:   { eq: 'maquina', ini: [20, 45], tope: [40, 90] },
  dominadas:   { eq: 'corporal', ini: 'Con la asistencia que te deje hacer 6 repeticiones limpias', tope: 'Peso corporal: nunca con lastre este ciclo' },
  domAsist:    { eq: 'corporal', ini: 'La asistencia que te deje hacer 6 repeticiones limpias', tope: 'Ir quitando asistencia, nunca con lastre' },
  remoInv:     { eq: 'corporal', ini: 'Barra alta (más fácil)', tope: 'Peso corporal: se hace más difícil bajando la barra, nunca con peso' },
  slam:        { eq: 'balon', ini: [3, 3], tope: [6, 6], nota: 'Balón de 3-4 kg.' },
  slamSuave:   { eq: 'balon', ini: [3, 3], tope: [4, 4] },
  pechoPared:  { eq: 'balon', ini: [3, 3], tope: [5, 5] },
  rotacional:  { eq: 'balon', ini: [3, 3], tope: [5, 5] },
  rotExtManc:  { eq: 'manc', ini: [1, 2.5], tope: [3, 5] },
  facepull:    { eq: 'maquina', ini: [5, 10], tope: [15, 30], nota: 'Si lo haces con banda: banda ligera → mediana.' },
  pallof:      { eq: 'maquina', ini: [5, 10], tope: [12.5, 25], nota: 'Si lo haces con banda: banda ligera → mediana.' },
  aductorMaq:  { eq: 'maquina', ini: [15, 30], tope: [30, 65] },
  prensa:      { eq: 'maquina', ini: [30, 65], tope: [80, 180], nota: 'Sin contar el carro de la máquina.' },
  hipMaq:      { eq: 'maquina', ini: [20, 45], tope: [50, 110] },
  remoMaq:     { eq: 'maquina', ini: [20, 45], tope: [40, 90] },
  rotExtPolea: { eq: 'maquina', ini: [2.5, 5], tope: [7.5, 15] },
  curlFem:     { eq: 'maquina', ini: [15, 30], tope: [35, 75] },
  talones:     { eq: 'maquina', ini: [20, 45], tope: [50, 110] },
  prensaUna:   { eq: 'maquina', ini: [15, 35], tope: [40, 90], nota: 'Sin contar el carro de la máquina.' },
  pressPecho:  { eq: 'maquina', ini: [15, 30], tope: [35, 75] },
  pressHombroMaq: { eq: 'maquina', ini: [10, 20], tope: [25, 55] },
  ytw:         { eq: 'banda' }, rotExt: { eq: 'banda' }, pasosBanda: { eq: 'banda' }, rotBanda: { eq: 'banda' }, slamCuerda: { eq: 'banda' },
  cajon:       { eq: 'cajon' }, cajonSentado: { eq: 'cajon' },
};

// ── Ejercicios ───────────────────────────────────────────────
// tr: transferencia · para: para qué sirve en el agua · como: 3 pasos · error: error común
// z / s: músculos principales / secundarios · carga: zonas que carga (para el chequeo de dolor)
// salto: cuenta contactos de salto · pot: ejercicio de potencia · tec: revisar técnica la primera semana
// check: lo que el instructor (o el video) debe mirar · casa: equipo en casa
export const EJ = {
  // ── Activación y movilidad ─────────────────────────────────
  m9090: { n: 'Movilidad de cadera 90/90', tr: ['rodilla', 'patada'], z: ['gluteo', 'gluteoMedio'], s: ['aductor'],
    para: 'Mejora la rotación de cadera que pide la patada de pecho.',
    como: ['Siéntate con las dos rodillas dobladas a 90°, una adelante y otra al lado.', 'Gira las rodillas al otro lado sin apoyar las manos.', 'Mantén el pecho alto todo el tiempo.'],
    error: 'Encorvar la espalda.', casa: 'Piso' },
  mtobillo: { n: 'Movilidad de tobillo en pared', tr: ['patada'], z: ['pantorrilla'], s: [],
    para: 'Tobillo flexible = pies que "agarran" más agua en la patada.',
    como: ['Pie a un puño de la pared.', 'Lleva la rodilla hacia la pared sin despegar el talón.', 'Vuelve y repite; aleja el pie si ya es fácil.'],
    error: 'Levantar el talón.', casa: 'Pared' },
  ytw: { n: 'Y-T-W con banda', tr: ['hombro'], z: ['deltoidesPost', 'trapecio'], s: [], carga: ['hombro'],
    para: 'Activa la parte de atrás del hombro y la escápula.',
    como: ['Brazos estirados al frente con la banda.', 'Forma una Y, luego una T y luego una W.', 'Aprieta los omóplatos en cada letra.'],
    error: 'Subir los hombros a las orejas.', casa: 'Banda elástica' },
  puente: { n: 'Puente de glúteo', tr: ['salida', 'patada'], z: ['gluteo'], s: ['femoral'],
    para: 'Despierta los glúteos antes de saltar.',
    como: ['Boca arriba, rodillas dobladas y pies apoyados.', 'Sube la cadera empujando con los talones.', 'Aprieta 2 s arriba y baja lento.'],
    error: 'Arquear la espalda baja.', casa: 'Piso' },
  balanceo: { n: 'Balanceo de piernas', tr: ['patada', 'rodilla'], z: ['gluteo', 'femoral'], s: ['aductor'],
    para: 'Suelta la cadera para la patada sin complicarte.',
    como: ['Apóyate en una pared o máquina con una mano.', 'Balancea la pierna adelante y atrás, suelta.', 'Cada vez un poco más alto, sin forzar.'],
    error: 'Arquear la espalda al llevar la pierna atrás.', casa: 'Pared' },
  pogo: { n: 'Saltos suaves en el sitio (pogo)', tr: ['salida'], z: ['pantorrilla'], s: [], carga: ['rodilla'],
    para: 'Prepara tobillos y tendones para saltar.',
    como: ['Piernas casi rectas.', 'Rebotes cortos y rápidos en la punta de los pies.', 'Toca el piso lo menos posible.'],
    error: 'Hundirse en cada rebote.', casa: 'Piso' },

  // ── Sesión A ───────────────────────────────────────────────
  cajon: { n: 'Salto al cajón', tr: ['salida'], z: ['cuadriceps', 'gluteo'], s: ['pantorrilla', 'femoral'], carga: ['rodilla'], salto: 1, pot: 1, tec: 1,
    para: 'Enseña a sacar fuerza máxima rápido, como en el bloque de salida.',
    como: ['Brazos atrás y baja un poco la cadera.', 'Salta explosivo y cae suave sobre el cajón.', 'Baja del cajón caminando, nunca saltando.'],
    error: 'Caer con las rodillas hacia adentro.',
    check: ['Cae suave, sin ruido', 'Rodillas alineadas con los pies al caer', 'Baja del cajón caminando'] },
  svertical: { n: 'Salto vertical', tr: ['salida'], z: ['cuadriceps', 'gluteo'], s: ['pantorrilla'], carga: ['rodilla'], salto: 1, pot: 1,
    para: 'Potencia hacia arriba sin depender del cajón.',
    como: ['Brazos atrás y baja un poco.', 'Salta lo más alto que puedas.', 'Cae suave con las rodillas alineadas.'],
    error: 'Caer con las piernas rígidas.' },
  scmpared: { n: 'Salto con contramovimiento a la pared', tr: ['salida'], z: ['cuadriceps', 'gluteo'], s: ['pantorrilla'], carga: ['rodilla'], salto: 1, pot: 1,
    para: 'Medir y entrenar la altura del salto.',
    como: ['De lado a la pared.', 'Baja rápido y salta tocando lo más alto que puedas.', 'Marca la altura y trata de llegar igual en cada salto.'],
    error: 'Hacer pausa abajo antes de saltar.' },
  longitud: { n: 'Salto de longitud con freno', tr: ['salida', 'viraje'], z: ['gluteo', 'cuadriceps'], s: ['femoral', 'pantorrilla'], carga: ['rodilla'], salto: 1, pot: 1, tec: 1,
    para: 'La misma extensión total que al empujar de la pared.',
    como: ['Pies al ancho de la cadera y brazos atrás.', 'Salta lo más lejos posible.', '"Clava" la caída y aguanta 2 s.'],
    error: 'Caer con el pecho muy adelante.',
    check: ['Cae con las rodillas alineadas', 'Pecho alto al caer, no muy adelante', 'Aguanta la caída 2 s sin dar pasos'] },
  longUna: { pp: 1, n: 'Salto de longitud a una pierna', tr: ['salida', 'viraje'], z: ['gluteo', 'cuadriceps'], s: ['gluteoMedio'], carga: ['rodilla'], salto: 1, pot: 1,
    para: 'Potencia y control a una pierna.',
    como: ['Párate en una pierna.', 'Salta adelante y cae con la misma pierna.', 'Aguanta 2 s estable.'],
    error: 'Rodilla hacia adentro al caer.' },
  cuclillas: { n: 'Saltos en cuclillas cortos', tr: ['salida'], z: ['cuadriceps', 'gluteo'], s: [], carga: ['rodilla'], salto: 1, pot: 1,
    para: 'Explosividad con menos impacto.',
    como: ['Baja a media sentadilla.', 'Salta corto hacia adelante.', 'Cae suave y vuelve a la posición.'],
    error: 'Caer con las rodillas hacia adentro.' },
  sstream: { n: 'Salto con piernas juntas en streamline', tr: ['viraje', 'streamline'], z: ['cuadriceps', 'gluteo'], s: ['deltoides', 'abdomen'], carga: ['rodilla'], salto: 1, pot: 1,
    para: 'Fuerza explosiva en la misma posición del empuje de pared.',
    como: ['Brazos arriba en streamline, piernas juntas.', 'Baja un poco y salta vertical.', 'No separes los brazos en ningún momento.'],
    error: 'Abrir los brazos.' },
  sjSinBrazos: { n: 'Squat jump sin brazos', tr: ['salida', 'viraje'], z: ['cuadriceps', 'gluteo'], s: [], carga: ['rodilla'], salto: 1, pot: 1,
    para: 'Potencia de piernas sin la ayuda de los brazos.',
    como: ['Manos en la cintura.', 'Pausa abajo en media sentadilla.', 'Salta explosivo y cae suave.'],
    error: 'Rebotar antes de saltar.' },
  goblet: { exp: 1, n: 'Sentadilla goblet (tempo 3-0-rápido)', tr: ['patada'], z: ['cuadriceps', 'gluteo'], s: ['aductor', 'abdomen'], carga: ['rodilla'], tec: 1,
    para: 'Fuerza base de cuádriceps y glúteo para la patada.',
    como: ['Mancuerna pegada al pecho, pies al ancho de los hombros.', 'Baja en 3 segundos con el pecho alto.', 'Sube rápido empujando el piso.'],
    error: 'Levantar los talones.',
    check: ['Talones pegados al piso', 'Rodillas siguen la dirección de los pies', 'Espalda recta y pecho alto'] },
  sentBarra: { exp: 1, n: 'Sentadilla con barra ligera', tr: ['patada'], z: ['cuadriceps', 'gluteo'], s: ['lumbar'], carga: ['rodilla', 'espalda'], tec: 1,
    para: 'Fuerza base de piernas con barra.',
    como: ['Barra sobre la parte alta de la espalda.', 'Baja controlado con el pecho alto.', 'Sube rápido.'],
    error: 'Redondear la espalda.',
    check: ['Espalda recta', 'Talones en el piso', 'Rodillas alineadas'] },
  smith: { exp: 1, n: 'Sentadilla en Smith', tr: ['patada'], z: ['cuadriceps', 'gluteo'], s: [], carga: ['rodilla'],
    para: 'Fuerza de piernas con la barra guiada.',
    como: ['Pies un poco adelante de la barra.', 'Baja controlado.', 'Sube rápido.'],
    error: 'Levantar los talones.' },
  puente1: { n: 'Puente de glúteo a una pierna', tr: ['patada', 'salida'], z: ['gluteo'], s: ['femoral'],
    para: 'Glúteo fuerte = patada más potente.',
    como: ['Boca arriba, una pierna estirada al aire.', 'Empuja con el talón del pie apoyado.', 'Sube con la cadera nivelada.'],
    error: 'Girar la cadera.', casa: 'Piso' },
  hipthrust: { exp: 1, n: 'Hip thrust con mancuerna', tr: ['patada', 'salida'], z: ['gluteo'], s: ['femoral'],
    para: 'Glúteo fuerte para empujar.',
    como: ['Espalda alta apoyada en el banco, mancuerna sobre la cadera.', 'Sube la cadera hasta quedar recto.', 'Aprieta 1 s arriba.'],
    error: 'Arquear la espalda baja.' },
  sumo: { pp: 1, n: 'Sentadilla sumo con mancuerna', tr: ['patada'], z: ['aductor', 'gluteo'], s: ['cuadriceps'], carga: ['rodilla'],
    para: 'Aductores y glúteo: los músculos del cierre de la patada.',
    como: ['Pies bien abiertos, puntas hacia afuera.', 'Mancuerna colgando entre las piernas.', 'Baja con las rodillas siguiendo a los pies.'],
    error: 'Rodillas hacia adentro.' },
  aductorMaq: { n: 'Aductor en máquina', tr: ['patada', 'rodilla'], maq: 1, z: ['aductor'], s: [], carga: ['rodilla'],
    para: 'Aductores fuertes: el cierre de la patada de pecho y rodillas protegidas.',
    como: ['Siéntate con la espalda apoyada.', 'Cierra las piernas controlado.', 'Abre lento, sin dejar que el peso golpee.'],
    error: 'Usar mucho peso y rebotar.' },
  copen: { n: 'Plancha Copenhague', tr: ['rodilla', 'patada'], z: ['aductor', 'oblicuos'], s: ['abdomen'], carga: ['rodilla'], tec: 1,
    para: 'Aductores fuertes protegen la rodilla del nadador de pecho.',
    como: ['De lado, antebrazo en el piso.', 'Pierna de arriba sobre el banco.', 'Sube la cadera hasta quedar recto.'],
    error: 'Dejar caer la cadera.',
    check: ['Cuerpo en línea recta', 'Cadera arriba, sin caer', 'Sin dolor en la cara interna de la rodilla'], casa: 'Sofá' },
  copenRod: { n: 'Copenhague con rodilla apoyada', tr: ['rodilla'], z: ['aductor', 'oblicuos'], s: [],
    para: 'Versión más fácil para proteger la rodilla.',
    como: ['De lado, antebrazo en el piso.', 'Rodilla de arriba apoyada en el banco.', 'Sube la cadera y aguanta.'],
    error: 'Dejar caer la cadera.' },
  balonRod: { n: 'Apretar balón entre rodillas', tr: ['rodilla'], z: ['aductor'], s: [],
    para: 'Activa los aductores sin carga.',
    como: ['Boca arriba con un balón entre las rodillas.', 'Aprieta fuerte.', 'Aguanta sin aguantar la respiración.'],
    error: 'Aguantar la respiración.' },
  pallof: { n: 'Pallof press', tr: ['streamline'], z: ['oblicuos', 'abdomen'], s: [],
    para: 'Core que no se tuerce = cuerpo alineado en el agua.',
    como: ['De lado a la polea o banda, manos al pecho.', 'Empuja al frente sin girar.', 'Vuelve lento al pecho.'],
    error: 'Rotar el torso.' },
  plancha: { n: 'Plancha frontal', tr: ['streamline'], z: ['abdomen'], s: ['oblicuos', 'deltoides'], casa: 'Piso',
    para: 'Core firme = cuerpo recto y alto en el agua.',
    como: ['Antebrazos en el piso, codos debajo de los hombros.', 'Cuerpo recto de la cabeza a los talones.', 'Aprieta el abdomen y respira.'],
    error: 'Dejar caer la cadera o subirla mucho.' },
  planchaLat: { n: 'Plancha lateral', tr: ['streamline'], z: ['oblicuos'], s: ['abdomen'],
    para: 'Core lateral firme.',
    como: ['De lado sobre el antebrazo.', 'Cadera arriba, cuerpo recto.', 'Aguanta respirando.'],
    error: 'Dejar caer la cadera.' },

  prensa: { exp: 1, n: 'Prensa de piernas', tr: ['salida', 'viraje'], z: ['cuadriceps', 'gluteo'], s: ['aductor', 'femoral'], carga: ['rodilla'], maq: 1,
    para: 'Fuerza de piernas segura entrenando solo: el mismo empuje que haces contra la pared en cada viraje.',
    como: ['Espalda y cadera pegadas al respaldo, pies al ancho de los hombros.', 'Baja hasta que las rodillas queden a 90° sin despegar la cadera.', 'Empuja con todo el pie, sin bloquear las rodillas arriba.'],
    error: 'Bloquear las rodillas arriba o despegar la cadera del asiento.',
    check: ['Cadera pegada al asiento', 'Rodillas alineadas con los pies', 'Sin bloquear las rodillas al subir'] },
  hipMaq: { exp: 1, n: 'Hip thrust en máquina', tr: ['patada', 'salida'], z: ['gluteo'], s: ['femoral'], maq: 1,
    para: 'Glúteo fuerte = patada de pecho más potente y mejor salida.',
    como: ['Espalda alta apoyada y el rodillo sobre la cadera.', 'Sube la cadera hasta quedar recto de hombros a rodillas.', 'Aprieta 1 s arriba y baja controlado.'],
    error: 'Arquear la espalda baja en vez de subir con el glúteo.' },
  remoMaq: { exp: 1, n: 'Remo en máquina', tr: ['brazada'], z: ['dorsal', 'trapecio'], s: ['biceps'], maq: 1,
    para: 'Espalda media fuerte para sostener la postura en el agua.',
    como: ['Pecho contra el apoyo.', 'Jala con los codos hacia atrás.', 'Aprieta los omóplatos y vuelve lento.'],
    error: 'Despegar el pecho del apoyo.' },
  rotExtPolea: { n: 'Rotación externa en polea', tr: ['hombro'], z: ['deltoidesPost'], s: [], maq: 1,
    para: 'Prevención del hombro de nadador con carga constante.',
    como: ['De lado a la polea, a la altura del codo.', 'Codo pegado al cuerpo a 90°, gira la mano hacia afuera.', 'Vuelve lento, sin separar el codo.'],
    error: 'Separar el codo del cuerpo.' },

  curlFem: { exp: 1, n: 'Curl femoral en máquina', tr: ['patada', 'rodilla'], z: ['femoral'], s: ['pantorrilla'], maq: 1,
    para: 'Femorales fuertes: protegen la rodilla y dan potencia al final de la patada.',
    como: ['Ajusta el rodillo justo arriba de los talones.', 'Dobla las rodillas llevando los talones hacia el glúteo.', 'Baja lento en 2-3 segundos.'],
    error: 'Levantar la cadera del asiento para ayudarte.' },
  talones: { exp: 1, n: 'Elevación de talones en máquina', tr: ['salida', 'viraje'], z: ['pantorrilla'], s: [], maq: 1,
    para: 'Pantorrilla y tobillo fuertes para el último empuje de la salida y del viraje. Ayuda a sostener el arco del pie.',
    como: ['Puntas de los pies en el borde, talones en el aire.', 'Sube lo más alto que puedas en puntas.', 'Baja lento hasta sentir el estiramiento.'],
    error: 'Rebotar abajo o doblar las rodillas.' },
  prensaUna: { exp: 1, n: 'Prensa a una pierna', tr: ['salida', 'viraje'], z: ['cuadriceps', 'gluteo'], s: [], carga: ['rodilla'], maq: 1,
    para: 'Fuerza a una pierna sin tener que equilibrarte de pie.',
    como: ['Un pie en el centro de la plataforma.', 'Baja hasta 90° sin despegar la cadera.', 'Empuja sin bloquear la rodilla.'],
    error: 'Dejar que la rodilla se vaya hacia adentro.' },
  pressPecho: { exp: 1, n: 'Press de pecho en máquina', tr: ['brazada', 'salida'], z: ['pecho', 'triceps'], s: ['deltoides'], carga: ['hombro'], maq: 1,
    para: 'Empuje fuerte para el recobro de la brazada de pecho y la salida.',
    como: ['Agarres a la altura del pecho, espalda pegada al respaldo.', 'Empuja al frente sin bloquear los codos.', 'Vuelve lento, sin pasar la línea del pecho.'],
    error: 'Despegar los hombros del respaldo.' },
  pressHombroMaq: { exp: 1, n: 'Press de hombros en máquina', tr: ['streamline', 'hombro'], z: ['deltoides', 'triceps'], s: ['trapecio'], carga: ['hombro'], maq: 1,
    para: 'Fuerza por encima de la cabeza para un streamline firme, con la espalda apoyada.',
    como: ['Espalda pegada al respaldo, agarres a la altura de los hombros.', 'Empuja arriba sin bloquear los codos.', 'Baja controlado hasta la altura de las orejas.'],
    error: 'Arquear la espalda baja.' },

  // ── Sesión B ───────────────────────────────────────────────
  slam: { n: 'Slam con balón medicinal', tr: ['brazada', 'sprint'], z: ['dorsal', 'abdomen'], s: ['triceps', 'deltoides'], carga: ['hombro'], pot: 1, tec: 1,
    para: 'Tirón explosivo de dorsales y core, como el agarre del agua.',
    como: ['Balón arriba en streamline.', 'Lánzalo al piso con todo usando el abdomen.', 'Recógelo con la espalda recta.'],
    error: 'Doblar solo los brazos sin usar el core.',
    check: ['El movimiento sale del abdomen, no solo de los brazos', 'Espalda recta al recoger el balón', 'Balón arriba en streamline al empezar'] },
  slamCuerda: { n: 'Slam con cuerda o banda', tr: ['brazada', 'sprint'], z: ['dorsal', 'abdomen'], s: ['triceps'], carga: ['hombro'], pot: 1,
    para: 'Tirón explosivo sin balón.',
    como: ['Brazos arriba con la cuerda o banda.', 'Jala hacia abajo explosivo.', 'Usa el abdomen.'],
    error: 'Usar solo los brazos.' },
  slamSuave: { n: 'Slam suave', tr: ['brazada'], z: ['dorsal', 'abdomen'], s: [], carga: ['hombro'], pot: 1,
    para: 'Despertar el tirón sin cansarte.',
    como: ['Balón arriba.', 'Lánzalo al piso rápido pero suave.', 'Recógelo con la espalda recta.'],
    error: 'Hacerlo con todo: hoy es suave.' },
  pechoPared: { n: 'Lanzamiento de pecho contra la pared', tr: ['brazada'], z: ['pecho', 'triceps'], s: ['deltoides'], carga: ['hombro'], pot: 1, tec: 1,
    para: 'Potencia de pecho y tríceps para el recobro rápido.',
    como: ['Frente a la pared con el balón en el pecho.', 'Lánzalo fuerte a la pared.', 'Atrápalo y repite.'],
    error: 'Lanzar con los codos muy abiertos.',
    check: ['Codos cerca del cuerpo', 'Lanzamiento rápido desde el pecho', 'Abdomen apretado'] },
  flexExpl: { n: 'Flexiones explosivas', tr: ['brazada', 'salida'], z: ['pecho', 'triceps'], s: ['deltoides', 'abdomen'], carga: ['hombro'], pot: 1, casa: 'Piso',
    para: 'Empuje rápido para el recobro y la salida.',
    como: ['Posición de plancha con manos al ancho de los hombros.', 'Baja controlado.', 'Empuja tan fuerte que las manos se despeguen.'],
    error: 'Cadera caída.' },
  flexPalmada: { n: 'Flexiones con palmada', tr: ['brazada'], z: ['pecho', 'triceps'], s: [], carga: ['hombro'], pot: 1,
    para: 'Empuje explosivo.',
    como: ['Baja controlado.', 'Empuja fuerte y da una palmada.', 'Cae suave con los codos un poco doblados.'],
    error: 'Cadera caída.' },
  flexRapidas: { n: 'Flexiones normales rápidas', tr: ['brazada'], z: ['pecho', 'triceps'], s: [], carga: ['hombro'], pot: 1,
    para: 'Empuje rápido con menos impacto.',
    como: ['Cuerpo recto.', 'Baja controlado.', 'Sube lo más rápido que puedas.'],
    error: 'Cadera caída.' },
  dominadas: { exp: 1, n: 'Dominadas', tr: ['brazada', 'sprint'], z: ['dorsal', 'biceps'], s: ['trapecio', 'antebrazo'], carga: ['hombro'], tec: 1,
    para: 'El tirón principal del nado.',
    como: ['Cuélgate con los brazos estirados.', 'Sube llevando el pecho a la barra.', 'Baja en 3 segundos.'],
    error: 'Balancearse.',
    check: ['Empieza con los brazos estirados', 'Sin balanceo ni patadas', 'Baja lento, en 3 segundos'] },
  domAsist: { exp: 1, n: 'Dominadas asistidas en máquina', tr: ['brazada', 'sprint'], z: ['dorsal', 'biceps'], s: [], carga: ['hombro'],
    para: 'El mismo tirón con ayuda.',
    como: ['Rodillas o pies en la asistencia (máquina o banda).', 'Pecho a la barra.', 'Baja lento.'],
    error: 'Balancearse.' },
  jalon: { exp: 1, n: 'Jalón al pecho', tr: ['brazada', 'sprint'], maq: 1, z: ['dorsal'], s: ['biceps'], carga: ['hombro'],
    para: 'Fuerza del tirón en máquina.',
    como: ['Pecho alto, agarre un poco más ancho que los hombros.', 'Baja la barra al pecho alto.', 'Sube controlado.'],
    error: 'Echar el torso muy atrás.' },
  remoInv: { n: 'Remo invertido', tr: ['brazada', 'hombro'], z: ['dorsal', 'trapecio'], s: ['biceps', 'deltoidesPost'],
    para: 'Espalda media para una postura fuerte en el agua.',
    como: ['Cuélgate bajo una barra con el cuerpo recto.', 'Lleva el pecho a la barra.', 'Baja controlado.'],
    error: 'Cadera caída.' },
  remoMano: { exp: 1, n: 'Remo con mancuerna a una mano', tr: ['brazada'], z: ['dorsal'], s: ['biceps', 'trapecio'],
    para: 'Espalda fuerte, un lado a la vez.',
    como: ['Rodilla y mano en el banco.', 'Jala la mancuerna hacia la cadera.', 'Baja lento.'],
    error: 'Girar el torso.', maq: 0 },
  remoPolea: { exp: 1, n: 'Remo en polea sentado', tr: ['brazada'], maq: 1, z: ['dorsal', 'trapecio'], s: ['biceps'],
    para: 'Espalda media.',
    como: ['Sentado con el pecho alto.', 'Jala al abdomen con los codos pegados.', 'Aprieta los omóplatos.'],
    error: 'Balancear el torso.' },
  pullover: { n: 'Pullover con mancuerna', tr: ['brazada'], z: ['dorsal', 'pecho'], s: ['triceps'], carga: ['hombro'],
    para: 'Imita el barrido hacia adentro de la brazada.',
    como: ['Acostado en el banco, mancuerna arriba con las dos manos.', 'Bájala detrás de la cabeza con los brazos casi rectos.', 'Tráela de vuelta hasta el pecho.'],
    error: 'Doblar mucho los codos.' },
  pulloverPolea: { exp: 1, n: 'Pullover en polea con cuerda', tr: ['brazada'], maq: 1, z: ['dorsal'], s: ['triceps'], carga: ['hombro'],
    para: 'El barrido de la brazada en polea.',
    como: ['De pie frente a la polea alta.', 'Brazos casi rectos, baja la cuerda hasta los muslos.', 'Sube lento.'],
    error: 'Doblar los codos.' },
  rotExt: { n: 'Rotación externa con banda', tr: ['hombro'], z: ['deltoidesPost'], s: [], casa: 'Banda elástica',
    para: 'Prevención del "hombro de nadador".',
    como: ['Codo pegado al cuerpo, doblado a 90°.', 'Gira la mano hacia afuera lento.', 'Vuelve controlado.'],
    error: 'Separar el codo del cuerpo.' },
  rotExtManc: { n: 'Rotación externa acostado con mancuerna', tr: ['hombro'], z: ['deltoidesPost'], s: [],
    para: 'Prevención del "hombro de nadador".',
    como: ['Acostado de lado, codo pegado a la cintura.', 'Sube la mancuerna girando el brazo.', 'Baja lento.'],
    error: 'Separar el codo.' },
  facepull: { n: 'Face pull con banda o polea', tr: ['hombro', 'streamline'], z: ['deltoidesPost', 'trapecio'], s: [],
    para: 'Postura y hombro trasero.',
    como: ['Agarra la cuerda o banda a la altura de la cara.', 'Jala hacia la cara abriendo las manos.', 'Aprieta los omóplatos.'],
    error: 'Arquear la espalda.' },
  ytwInclinado: { n: 'Y-T-W boca abajo en banco inclinado', tr: ['hombro'], z: ['deltoidesPost', 'trapecio'], s: [],
    para: 'Hombro trasero y escápula.',
    como: ['Boca abajo en el banco inclinado.', 'Forma Y, T y W con los brazos.', 'Aprieta los omóplatos.'],
    error: 'Subir los hombros.' },
  hollow: { n: 'Hollow hold', tr: ['streamline'], z: ['abdomen'], s: ['oblicuos'], casa: 'Piso',
    para: 'La posición de cuerpo más hidrodinámica.',
    como: ['Boca arriba, espalda baja pegada al piso.', 'Brazos y piernas extendidos y despegados.', 'Aguanta respirando.'],
    error: 'Despegar la espalda baja.' },
  hollowRod: { n: 'Hollow con rodillas dobladas', tr: ['streamline'], z: ['abdomen'], s: [],
    para: 'Versión más fácil del hollow.',
    como: ['Boca arriba, espalda baja pegada al piso.', 'Rodillas dobladas a 90° en el aire.', 'Aguanta.'],
    error: 'Despegar la espalda baja.' },

  // ── Sesión C ───────────────────────────────────────────────
  squatJump: { n: 'Squat jump', tr: ['salida', 'viraje'], z: ['cuadriceps', 'gluteo'], s: ['pantorrilla'], carga: ['rodilla'], salto: 1, pot: 1,
    para: 'Potencia desde abajo sin rebote, como al empujar la pared.',
    como: ['Baja a media sentadilla.', 'Pausa 2 s abajo.', 'Salta explosivo y cae suave.'],
    error: 'Rebotar antes de saltar.' },
  cajonSentado: { n: 'Salto al cajón desde sentado', tr: ['salida'], z: ['cuadriceps', 'gluteo'], s: [], carga: ['rodilla'], salto: 1, pot: 1,
    para: 'Potencia desde cero, sin rebote.',
    como: ['Sentado en un banco frente al cajón.', 'Párate y salta explosivo al cajón.', 'Baja caminando.'],
    error: 'Caer con las rodillas hacia adentro.' },
  patinador: { pp: 1, n: 'Salto lateral de patinador', tr: ['viraje', 'patada'], z: ['gluteoMedio', 'cuadriceps'], s: ['aductor'], carga: ['rodilla'], salto: 1, pot: 1,
    para: 'Potencia lateral y control de rodilla.',
    como: ['Párate en una pierna.', 'Salta de lado y cae en la otra pierna.', 'Quédate estable 1 s antes del siguiente.'],
    error: 'Rodilla hacia adentro al caer.' },
  pasosBanda: { n: 'Pasos laterales con banda', tr: ['rodilla'], z: ['gluteoMedio'], s: [],
    para: 'Glúteo medio para rodillas estables.',
    como: ['Banda arriba de las rodillas.', 'Media sentadilla.', 'Pasos laterales sin juntar los pies.'],
    error: 'Juntar los pies.' },
  rotacional: { n: 'Lanzamiento rotacional de balón a la pared', tr: ['sprint'], z: ['oblicuos', 'abdomen'], s: ['gluteo', 'deltoides'], carga: ['espalda'], pot: 1, tec: 1,
    para: 'Rotación potente del tronco para el sprint de libre.',
    como: ['De lado a la pared con el balón a la altura de la cadera.', 'Gira desde la cadera.', 'Lanza fuerte y atrapa.'],
    error: 'Lanzar solo con los brazos.',
    check: ['El giro empieza en la cadera', 'Pies firmes en el piso', 'Brazos casi rectos, no solo brazos'] },
  rotBanda: { n: 'Rotaciones con banda rápidas', tr: ['sprint'], z: ['oblicuos'], s: [],
    para: 'Rotación del tronco sin balón.',
    como: ['De lado a la banda.', 'Gira rápido desde la cadera.', 'Vuelve controlado.'],
    error: 'Mover solo los brazos.' },
  rdl: { exp: 1, pp: 1, n: 'Peso muerto rumano con mancuernas', tr: ['salida', 'patada'], z: ['femoral', 'gluteo'], s: ['lumbar'], carga: ['espalda'], tec: 1,
    para: 'Cadena posterior para impulsar en la salida y el viraje.',
    como: ['Mancuernas pegadas a las piernas, rodillas un poco dobladas.', 'Lleva la cadera atrás con la espalda recta.', 'Sube apretando el glúteo.'],
    error: 'Redondear la espalda.',
    check: ['Espalda recta todo el tiempo', 'La cadera va atrás, no hacia abajo', 'Mancuernas pegadas a las piernas'] },
  puentePies: { n: 'Puente de glúteo con pies elevados', tr: ['salida', 'patada'], z: ['gluteo', 'femoral'], s: [],
    para: 'Cadena posterior sin cargar la espalda.',
    como: ['Pies sobre un banco.', 'Sube la cadera.', 'Aprieta arriba y baja lento.'],
    error: 'Arquear la espalda baja.' },
  hiper: { n: 'Hiperextensiones', tr: ['salida'], z: ['lumbar', 'gluteo'], s: ['femoral'], carga: ['espalda'],
    para: 'Espalda baja y glúteo.',
    como: ['Cadera en el apoyo.', 'Baja con la espalda recta.', 'Sube hasta quedar recto, sin pasarte.'],
    error: 'Subir de más arqueando la espalda.' },
  bulgara: { exp: 1, pp: 1, n: 'Sentadilla búlgara', tr: ['patada', 'salida'], z: ['cuadriceps', 'gluteo'], s: ['aductor', 'gluteoMedio'], carga: ['rodilla'], tec: 1,
    para: 'Fuerza a una pierna y equilibrio.',
    como: ['Pie de atrás apoyado en el banco.', 'Baja vertical, como un ascensor.', 'Sube empujando con el pie de adelante.'],
    error: 'Inclinarse demasiado.',
    check: ['Torso casi vertical', 'Rodilla de adelante alineada con el pie', 'Baja controlado, sin rebotar'] },
  zancada: { exp: 1, pp: 1, n: 'Zancada reversa', tr: ['patada'], z: ['cuadriceps', 'gluteo'], s: [], carga: ['rodilla'],
    para: 'Fuerza a una pierna.',
    como: ['Da un paso atrás.', 'Baja la rodilla de atrás cerca del piso.', 'Vuelve empujando con el pie de adelante.'],
    error: 'Rodilla de adelante hacia adentro.' },
  stepup: { pp: 1, n: 'Step-up', tr: ['salida'], z: ['cuadriceps', 'gluteo'], s: [], carga: ['rodilla'],
    para: 'Fuerza a una pierna.',
    como: ['Un pie arriba del cajón.', 'Sube empujando con ese pie.', 'Baja lento.'],
    error: 'Impulsarte con el pie de abajo.' },
  pressMil: { exp: 1, n: 'Press militar con mancuernas de pie', tr: ['streamline', 'hombro'], z: ['deltoides', 'triceps'], s: ['trapecio', 'abdomen'], carga: ['hombro', 'espalda'], tec: 1,
    para: 'Fuerza por encima de la cabeza para un streamline firme.',
    como: ['De pie, mancuernas a la altura de los hombros.', 'Aprieta el abdomen.', 'Empuja arriba sin arquear la espalda.'],
    error: 'Arquear la espalda baja.',
    check: ['Abdomen apretado, espalda sin arquear', 'Brazos terminan estirados arriba de la cabeza', 'Baja controlado a los hombros'] },
  landmine: { n: 'Press landmine a una mano', tr: ['streamline', 'hombro'], z: ['deltoides'], s: ['triceps', 'oblicuos'], carga: ['hombro'],
    para: 'Empuje arriba más amable con el hombro.',
    como: ['Punta de la barra a la altura del hombro.', 'Empuja hacia arriba y adelante.', 'Baja controlado.'],
    error: 'Girar el torso.' },
  superman: { n: 'Superman en streamline', tr: ['streamline'], z: ['lumbar', 'gluteo'], s: ['deltoidesPost'], casa: 'Piso',
    para: 'Espalda y glúteos para mantener el cuerpo alto en el agua.',
    como: ['Boca abajo con los brazos en streamline.', 'Despega el pecho y las piernas.', 'Aguanta mirando al piso.'],
    error: 'Mirar hacia arriba.' },
  birddog: { n: 'Bird dog', tr: ['streamline'], z: ['lumbar', 'abdomen'], s: ['gluteo'],
    para: 'Core estable mientras brazos y piernas se mueven.',
    como: ['En cuatro apoyos.', 'Estira el brazo y la pierna contrarios.', 'Vuelve lento y cambia.'],
    error: 'Arquear la espalda.' },
  deadbug: { n: 'Dead bug', tr: ['streamline', 'patada'], z: ['abdomen'], s: ['oblicuos'], casa: 'Piso',
    para: 'Core que trabaja mientras las piernas se mueven.',
    como: ['Boca arriba, brazos al techo y rodillas a 90°.', 'Baja lento el brazo y la pierna contrarios.', 'Espalda baja pegada al piso.'],
    error: 'Despegar la espalda.' },

  // ── Movilidad, precompetencia y competencia ────────────────
  rana: { n: 'Estiramiento de aductores en rana', tr: ['patada', 'rodilla'], z: ['aductor'], s: [], casa: 'Piso',
    para: 'Aductores flexibles para una patada amplia.',
    como: ['En cuatro apoyos, abre las rodillas a los lados.', 'Lleva la cadera atrás despacio.', 'Respira y relaja.'],
    error: 'Forzar hasta que duela.' },
  dorsalPared: { n: 'Estiramiento de dorsal en la pared', tr: ['brazada', 'hombro'], z: ['dorsal'], s: [], casa: 'Pared',
    para: 'Dorsal suelto = brazada más larga.',
    como: ['Manos en la pared y da un paso atrás.', 'Baja el pecho con la cadera atrás.', 'Siente el estiramiento bajo la axila.'],
    error: 'Arquear la espalda baja.' },
  dorsalPuerta: { n: 'Estiramiento de dorsal en el marco de la puerta', tr: ['brazada', 'hombro'], z: ['dorsal'], s: [], casa: 'Marco de puerta',
    para: 'Dorsal suelto = brazada más larga.',
    como: ['Agarra el marco de la puerta con las manos a la altura de la cabeza.', 'Lleva la cadera atrás con las rodillas un poco dobladas.', 'Respira y aguanta.'],
    error: 'Forzar hasta que duela.' },
  toracica: { n: 'Rotación torácica en cuadrupedia', tr: ['sprint', 'hombro'], z: ['trapecio', 'oblicuos'], s: [], casa: 'Piso',
    para: 'Espalda alta móvil para rotar en libre.',
    como: ['En cuatro apoyos, una mano detrás de la cabeza.', 'Gira el codo hacia el techo.', 'Sigue el codo con la mirada.'],
    error: 'Girar desde la cadera.' },
  respPared: { n: 'Respiración con piernas en la pared', tr: [], z: [], s: [], casa: 'Pared',
    para: 'Baja el cansancio y ayuda a dormir.',
    como: ['Boca arriba con las piernas apoyadas en la pared.', 'Inhala 4 s por la nariz.', 'Bota el aire lento en 6 s.'],
    error: 'Respirar rápido.' },
  gatoCamello: { n: 'Gato-camello', tr: [], z: ['lumbar'], s: [], casa: 'Piso',
    para: 'Columna suelta y sin tensión.',
    como: ['En cuatro apoyos.', 'Redondea la espalda mirando al ombligo.', 'Luego húndela mirando al frente.'],
    error: 'Hacerlo rápido.' },
  movGeneral: { n: 'Movilidad de cadera, tobillo y hombro', tr: ['patada', 'hombro'], z: [], s: [],
    para: 'Despertar las articulaciones que más usas.',
    como: ['Círculos de cadera y tobillo.', 'Círculos de brazos y hombros.', 'Movimientos suaves, sin forzar.'],
    error: 'Hacerlo con prisa.' },
  circBrazos: { n: 'Círculos de brazos', tr: ['hombro'], z: ['deltoides'], s: [],
    para: 'Hombros calientes antes de nadar.',
    como: ['De pie, brazos estirados.', 'Círculos grandes hacia adelante.', 'Luego hacia atrás.'],
    error: 'Hacerlos muy rápido de entrada.' },
  salidaImag: { n: 'Salida imaginaria en streamline', tr: ['salida', 'streamline'], z: ['cuadriceps', 'gluteo'], s: [],
    para: 'Ensayar el gesto de la salida.',
    como: ['Posición de salida.', 'Impulso explosivo hacia adelante.', 'Termina en streamline perfecto.'],
    error: 'Abrir los brazos al final.' },

  // ── Plan B en casa ─────────────────────────────────────────
  sjCasa: { n: 'Squat jump sin peso', tr: ['salida', 'viraje'], z: ['cuadriceps', 'gluteo'], s: [], carga: ['rodilla'], salto: 1, pot: 1, casa: 'Piso',
    para: 'Mantener la potencia de la salida.',
    como: ['Media sentadilla.', 'Pausa 1 s.', 'Salta explosivo y cae suave.'],
    error: 'Caer con las rodillas hacia adentro.' },
  sentRapida: { n: 'Sentadilla rápida sin salto', tr: ['patada'], z: ['cuadriceps', 'gluteo'], s: [], carga: ['rodilla'], casa: 'Piso',
    para: 'Velocidad de piernas sin impacto.',
    como: ['Pies al ancho de los hombros.', 'Baja controlado.', 'Sube rápido.'],
    error: 'Levantar los talones.' },
  flexCasa: { n: 'Flexiones explosivas o rápidas', tr: ['brazada'], z: ['pecho', 'triceps'], s: [], carga: ['hombro'], pot: 1, casa: 'Piso',
    para: 'Empuje rápido para el recobro.',
    como: ['Cuerpo recto.', 'Baja controlado.', 'Sube lo más rápido que puedas.'],
    error: 'Cadera caída.' },
  bulgaraSofa: { pp: 1, n: 'Sentadilla búlgara con el pie en el sofá', tr: ['patada'], z: ['cuadriceps', 'gluteo'], s: [], carga: ['rodilla'], casa: 'Sofá · mochila opcional',
    para: 'Fuerza a una pierna en casa.',
    como: ['Pie de atrás en el sofá.', 'Baja vertical.', 'Sube empujando con el pie de adelante.'],
    error: 'Inclinarse demasiado.' },
  remoCasa: { n: 'Remo con banda o bajo una mesa firme', tr: ['brazada'], z: ['dorsal', 'trapecio'], s: ['biceps'], casa: 'Banda en la puerta o mesa firme',
    para: 'Mantener el tirón de la brazada.',
    como: ['Banda atada a la puerta (o acostado bajo una mesa firme).', 'Jala llevando los codos atrás.', 'Aprieta los omóplatos.'],
    error: 'Encoger los hombros.' },
  copenSofa: { n: 'Plancha Copenhague con la pierna en el sofá', tr: ['rodilla'], z: ['aductor', 'oblicuos'], s: [], carga: ['rodilla'], casa: 'Sofá',
    para: 'Aductores fuertes protegen la rodilla.',
    como: ['De lado, antebrazo en el piso.', 'Pierna de arriba sobre el sofá.', 'Sube la cadera y aguanta.'],
    error: 'Dejar caer la cadera.' },
  cardio: { n: 'Trote suave', tr: ['sprint'], z: ['cuadriceps', 'pantorrilla'], s: [], casa: 'Afuera o en el sitio',
    para: 'No perder la base aeróbica.',
    como: ['Ritmo en el que puedas hablar.', 'Respira tranquilo.', 'Si estás muy cansado, camina rápido.'],
    error: 'Ir muy rápido.' },
  cuerda: { n: 'Saltar cuerda por rondas', tr: ['sprint'], z: ['pantorrilla'], s: [], carga: ['rodilla'], casa: 'Cuerda',
    para: 'Base aeróbica sin salir de casa.',
    como: ['1 minuto saltando suave.', '1 minuto de descanso.', 'Repite 8 rondas.'],
    error: 'Saltar muy alto.' },
  brazadaBanda: { n: 'Brazada de pecho con banda', tr: ['brazada'], z: ['dorsal', 'pecho'], s: ['triceps'], casa: 'Banda atada al frente',
    para: 'Mantener el gesto y la fuerza de la brazada.',
    como: ['De pie e inclinado al frente, banda atada al frente.', 'Barrido afuera, barrido adentro.', 'Recobro rápido al frente.'],
    error: 'Hacer el recobro lento.' },
  patadaSeco: { n: 'Patada de pecho en seco', tr: ['patada'], z: ['gluteo', 'aductor'], s: ['femoral'], carga: ['rodilla'], casa: 'Cama',
    para: 'Mantener el gesto de la patada.',
    como: ['Boca abajo con la cadera al borde de la cama.', 'Patada lenta y completa.', 'Junta bien los pies al final.'],
    error: 'No juntar los pies al final.' },
  libreBanda: { n: 'Brazada de libre con banda', tr: ['sprint'], z: ['dorsal'], s: ['triceps'], casa: 'Banda atada al frente',
    para: 'Mantener el tirón del libre.',
    como: ['De pie e inclinado al frente.', 'Jala la banda hasta la cadera.', 'Un brazo a la vez.'],
    error: 'Doblar mucho el codo al empezar.' },
  streamPared: { n: 'Streamline en la pared', tr: ['streamline', 'hombro'], z: ['deltoides', 'trapecio'], s: [], casa: 'Pared',
    para: 'Hombros que llegan a un streamline perfecto.',
    como: ['Espalda pegada a la pared.', 'Brazos en streamline contra la pared.', 'Sube y baja sin despegar los brazos.'],
    error: 'Despegar la espalda baja.' },
};

// Las animaciones (poses clave de cada ejercicio) viven en js/poses.js

// ── Bloques ──────────────────────────────────────────────────
export const BLOQUES = {
  activacion: { n: 'Activación', c: 'var(--aqua)' },
  potencia:   { n: 'Potencia',   c: 'var(--coral)' },
  fuerza:     { n: 'Fuerza',     c: 'var(--azul)' },
  core:       { n: 'Core y prevención', c: 'var(--turq)' },
  movilidad:  { n: 'Movilidad',  c: 'var(--celeste)' },
  casa:       { n: 'En casa',    c: 'var(--turq)' },
  circuito:   { n: 'Circuito',   c: 'var(--salmon)' },
  final:      { n: 'Para cerrar', c: 'var(--turq)' },
};

// Prescripción: e (ejercicio) · s (series) · r (reps) o seg (segundos) · lado · d (descanso en s)
// alts: alternativas con su propia prescripción. Cifras de las semanas de construcción.
const P = (e, s, r, d = 0, x = {}) => ({ e, s, r, d, ...x });
const T = (e, s, seg, d = 0, x = {}) => ({ e, s, seg, d, ...x });

export const ACTIVACION = [
  P('balanceo', 2, 10, 0, { lado: 'pierna' }),
  P('mtobillo', 2, 10, 0, { lado: 'pie' }),
  P('circBrazos', 2, 10),
  P('puente', 2, 12),
  P('pogo', 2, 15),
];

export const SESIONES = {
  A: { n: 'Potencia de piernas', sub: 'Salidas, virajes y patada · con máquinas', c: 'var(--aqua)',
    potencia: [
      P('cajon', 4, 3, 90, { alts: [P('svertical', 4, 3, 90), P('scmpared', 4, 3, 90)] }),
      P('longitud', 4, 3, 90, { alts: [P('cuclillas', 4, 3, 90), P('svertical', 4, 3, 90)] }),
      P('sstream', 3, 4, 60, { alts: [P('sjSinBrazos', 3, 4, 60)] }),
    ],
    fuerza: [
      P('prensa', 4, 8, 120, { alts: [P('smith', 4, 8, 120), P('goblet', 4, 8, 120)] }),
      P('hipMaq', 4, 10, 90, { alts: [P('puente1', 3, 10, 60, { lado: 'pierna' }), P('hipthrust', 4, 10, 90)] }),
      P('curlFem', 3, 10, 75, { alts: [P('puentePies', 3, 12, 60), P('hiper', 3, 12, 75)] }),
      P('aductorMaq', 3, 12, 60, { alts: [P('sumo', 3, 10, 60)] }),
      P('talones', 3, 12, 60, { alts: [P('prensa', 3, 15, 60)] }),
    ],
    core: [
      T('plancha', 3, 30, 45, { alts: [T('hollow', 3, 20, 45)] }),
      T('planchaLat', 3, 20, 45, { lado: 'lado', alts: [P('deadbug', 3, 8, 45, { lado: 'lado' })] }),
    ],
  },
  B: { n: 'Potencia de tren superior', sub: 'Brazada y sprint · con máquinas', c: 'var(--azul)',
    potencia: [
      P('slam', 4, 5, 60, { alts: [P('slamCuerda', 4, 8, 60)] }),
      P('pechoPared', 4, 5, 60, { alts: [P('flexExpl', 3, 5, 90)] }),
      P('flexExpl', 3, 5, 90, { alts: [P('flexRapidas', 3, 8, 90), P('pressPecho', 3, 6, 90)] }),
    ],
    fuerza: [
      P('jalon', 4, 8, 120, { alts: [P('domAsist', 4, 6, 120), P('dominadas', 4, 5, 120)] }),
      P('remoPolea', 4, 10, 90, { alts: [P('remoMaq', 4, 10, 90), P('remoInv', 3, 8, 90)] }),
      P('pressPecho', 3, 10, 90, { alts: [P('flexRapidas', 3, 10, 90)] }),
      P('pulloverPolea', 3, 12, 60, { alts: [P('pullover', 3, 10, 60)] }),
      P('pressHombroMaq', 3, 10, 75, { alts: [P('pressMil', 3, 8, 75)] }),
    ],
    core: [
      P('rotExtPolea', 2, 15, 30, { lado: 'brazo', alts: [P('rotExt', 2, 15, 30, { lado: 'brazo' })] }),
      P('facepull', 3, 12, 45, { alts: [P('rotExt', 2, 15, 30, { lado: 'brazo' })] }),
      T('hollow', 3, [20, 30], 45, { alts: [T('hollowRod', 3, 30, 45)] }),
    ],
  },
  C: { n: 'Potencia y fuerza total', sub: 'Virajes y sprint · mancuernas y máquinas', c: 'var(--turq)',
    potencia: [
      P('squatJump', 4, 4, 90, { alts: [P('cajonSentado', 4, 3, 90)] }),
      P('svertical', 3, 4, 60, { alts: [P('patinador', 3, 4, 60, { lado: 'lado' }), P('pasosBanda', 3, 12, 60, { lado: 'lado' })] }),
      P('rotacional', 3, 5, 60, { lado: 'lado', alts: [P('rotBanda', 3, 8, 60, { lado: 'lado' })] }),
    ],
    fuerza: [
      P('goblet', 4, 8, 120, { alts: [P('prensa', 4, 8, 120), P('smith', 4, 8, 120)] }),
      P('curlFem', 4, 10, 90, { alts: [P('rdl', 3, 8, 120), P('hipMaq', 4, 10, 90), P('puentePies', 3, 12, 90)] }),
      P('prensaUna', 3, 10, 90, { lado: 'pierna', alts: [P('prensa', 3, 10, 90), P('zancada', 3, 8, 90, { lado: 'pierna' })] }),
      P('pressMil', 3, 10, 90, { alts: [P('pressHombroMaq', 3, 10, 90)] }),
      P('remoMano', 3, 10, 75, { lado: 'brazo', alts: [P('remoPolea', 3, 10, 75), P('remoInv', 3, 8, 75)] }),
    ],
    core: [
      T('superman', 3, 20, 45, { alts: [P('birddog', 3, 8, 45, { lado: 'lado' })] }),
      P('deadbug', 3, 8, 45, { lado: 'lado', alts: [T('hollow', 3, 20, 45)] }),
      T('balonRod', 3, 10, 30, { alts: [T('plancha', 3, 30, 45)] }),
    ],
  },
};

// Rutinas que no son de gimnasio
export const RUTINAS = {
  movilidad: { n: 'Movilidad corta', sub: '10-12 min · en casa o después del agua · sin equipo, salvo una banda', c: 'var(--celeste)', casa: true,
    bloques: [{ b: 'movilidad', items: [
      P('balanceo', 2, 10, 0, { lado: 'pierna' }), P('mtobillo', 2, 10, 0, { lado: 'pie' }), T('rana', 2, 30, 15),
      T('dorsalPared', 2, 30, 15, { lado: 'lado' }), P('toracica', 2, 8, 0, { lado: 'lado' }), P('circBrazos', 1, 10), T('respPared', 1, 120),
    ] }] },
  precomp: { n: 'Activación precompetencia', sub: '15 min · rápido y fresco, no cansa', c: 'var(--amarillo)',
    bloques: [
      { b: 'movilidad', items: [T('movGeneral', 1, 300)] },
      { b: 'potencia', items: [P('pogo', 2, 10, 30), P('svertical', 3, 2, 60), P('slamSuave', 2, 3, 45)] },
    ] },
  competencia: { n: 'Calentamiento en seco', sub: 'Antes de entrar al agua', c: 'var(--amarillo)',
    bloques: [{ b: 'activacion', items: [
      T('movGeneral', 1, 300), P('circBrazos', 1, 10), P('rotExt', 1, 10, 0, { lado: 'brazo' }), P('svertical', 1, 3), P('salidaImag', 1, 2),
    ] }] },
  noche: { n: 'Recuperación de la noche', sub: '8 min · después de competir', c: 'var(--celeste)', casa: true,
    bloques: [{ b: 'movilidad', items: [T('respPared', 1, 180), P('gatoCamello', 1, 10), T('rana', 1, 30), T('dorsalPared', 1, 30, 0, { lado: 'lado' })] }] },

  // Plan B en casa
  recuperacion: { n: 'Recuperación activa en casa', sub: '12-15 min · para cuando vienes muy cansado', c: 'var(--celeste)', casa: true,
    final: 'Hoy lo importante es dormir 9 horas.',
    bloques: [{ b: 'casa', items: [
      T('respPared', 1, 180), P('balanceo', 2, 10, 0, { lado: 'pierna' }), P('mtobillo', 2, 10, 0, { lado: 'pie' }),
      P('toracica', 2, 8, 0, { lado: 'lado' }), T('dorsalPuerta', 2, 30, 15, { lado: 'lado' }), T('rana', 2, 30, 15), P('gatoCamello', 1, 10),
    ] }] },
  forma: { n: 'Mantener la forma en casa', sub: '20-25 min · circuito de 3 rondas con 60 s de descanso entre rondas', c: 'var(--salmon)', casa: true,
    bloques: [
      { b: 'circuito', rondas: 3, descansoRonda: 60, items: [
        P('pogo', 3, 15), P('sjCasa', 3, 5, 0, { alts: [P('cuclillas', 3, 5)] }), P('flexCasa', 3, 8),
        P('sentRapida', 3, 12), P('puente1', 3, 10, 0, { lado: 'pierna' }), P('remoCasa', 3, 12),
        T('planchaLat', 3, 15, 0, { lado: 'lado' }), T('hollow', 3, 25),
      ] },
      { b: 'final', items: [P('rotExt', 2, 15, 30, { lado: 'brazo' })] },
    ] },
  agua: { n: 'Mantener el agua en seco', sub: '25-30 min · para cuando faltaste a la piscina', c: 'var(--aqua)', casa: true,
    bloques: [
      { b: 'casa', items: [
        T('cardio', 1, 900, 0, { alts: [T('cuerda', 8, 60, 60)] }),
        P('brazadaBanda', 3, 15, 45), P('patadaSeco', 3, 10, 45), P('libreBanda', 3, 20, 45, { lado: 'brazo' }),
        P('streamPared', 3, 10, 30), T('superman', 3, 20, 30), P('mtobillo', 2, 10, 0, { lado: 'pie' }),
      ] },
    ] },
};

// ── Periodización ────────────────────────────────────────────
// p / f: series de potencia / fuerza que se suman o restan a la cifra base (construcción)
export const FASES = {
  tecnica:    { n: 'Técnica', c: 'var(--aqua)', p: -1, f: -1, core: 0, rpe: '6', tope: 30,
    txt: 'Aprende a moverte bien. Pocas series y técnica perfecta.' },
  construir:  { n: 'Construir', c: 'var(--turq)', p: 0, f: 0, core: 0, rpe: '7', tope: 40,
    txt: 'Subimos el trabajo. Saltos frescos y fuerza dejando 2-3 repeticiones de reserva.' },
  construir2: { n: 'Construir +', c: 'var(--turq)', p: 0, f: 0, core: 0, rpe: '7', tope: 40,
    txt: 'Mismo trabajo, más calidad. Si la sesión pasada te salió limpia, prueba un escalón más.' },
  pico:       { n: 'Pico', c: 'var(--coral)', p: 0, f: 0, core: 0, rpe: '7-8', tope: 45,
    txt: 'Máxima intención en cada salto. Un poco más de peso, nunca al fallo.' },
  descarga:   { n: 'Descarga', c: 'var(--amarillo)', p: -1, f: -1, core: -1, rpe: '6', tope: 25, peso: 0.85,
    txt: 'Menos volumen, misma velocidad. Tu cuerpo está asimilando el trabajo.' },
  puesta:     { n: 'Puesta a punto', c: 'var(--lila)', p: 0, f: null, core: -1, rpe: '5', tope: 12, peso: 0.5,
    txt: 'Sesiones cortas, rápidas y frescas. Nada nuevo y nada que te deje adolorido.' },
  competencia: { n: 'Competencia', c: 'var(--amarillo)', txt: '¡A nadar! Calentamiento en seco antes de entrar al agua y recuperación en la noche.' },
  despues:    { n: 'Después', c: 'var(--txt2)', txt: 'Ciclo terminado. Descansa unos días y arma tu próximo objetivo en Ajustes.' },
  antes:      { n: 'Antes del plan', c: 'var(--txt2)', txt: 'El plan todavía no arranca. Mientras, puedes hacer la movilidad corta.' },
};

// Ejercicios en los que conviene que alguien te vea la técnica la primera vez (solo sugerencia)
export const SUGERIR = ['cajon', 'longitud', 'rdl', 'goblet', 'slam', 'rotacional', 'pressMil'];

// ── Guía ─────────────────────────────────────────────────────
export const REGLAS_PARAR = [
  { t: 'Dolor agudo o punzante', d: 'En especial en la cara interna de la rodilla, el hombro o la espalda baja. Para y avísale a tu entrenador.' },
  { t: 'Mareo o técnica que se rompe', d: 'Si te mareas o la técnica se daña por cansancio, termina ese ejercicio.' },
  { t: 'Molestias del día siguiente', d: 'Las molestias musculares normales no son lesión. Si duran más de 3 días, avisa.' },
];

export const REGLAS_ENTRENADOR = [
  'Fuerza explosiva: en todos los ejercicios de fuerza baja controlado (2 s) y sube lo más rápido que puedas con técnica limpia. Si la velocidad cae mucho, el peso es demasiado.',
  'Calidad antes que cansancio: los saltos y lanzamientos se hacen frescos, rápidos y con descanso completo. Si la velocidad baja, se termina el ejercicio.',
  'Nunca al fallo. En fuerza siempre te deben sobrar 2-3 repeticiones (RPE 6-8).',
  'Técnica antes que peso. A los 16 años lo prioritario es aprender a moverte explosivo, no levantar el máximo.',
  'Nada de potencia de piernas (sesión A) el día antes de una sesión dura de velocidad o patada en el agua. Si coincide, se mueve.',
  'Si el seco es el mismo día que el agua, mejor hazlo después de nadar, o con al menos 4-6 horas de diferencia.',
  'Dolor de rodilla (cara interna) u hombro es motivo para parar y avisarle a tu entrenador de natación.',
  'Este plan complementa lo que manda tu entrenador de natación y no lo reemplaza. Enséñaselo.',
  'Duerme 8-10 horas y come suficiente: comida real en cada comida, con proteína y carbohidrato. Sin suplementos.',
];

export const RPE = [
  [1, 'Nada'], [2, 'Muy suave'], [3, 'Suave'], [4, 'Cómodo'], [5, 'Algo de esfuerzo'],
  [6, 'Me sobraban 4'], [7, 'Me sobraban 3'], [8, 'Me sobraban 2'], [9, 'Me sobraba 1'], [10, 'Al máximo'],
];

// ── Natación: pruebas individuales ───────────────────────────
// [id del estilo, nombre, distancias]. El 100 combinado solo existe en piscina corta (25 m).
export const ESTILOS = [
  ['libre', 'Libre', [50, 100, 200, 400, 800, 1500]],
  ['espalda', 'Espalda', [50, 100, 200]],
  ['pecho', 'Pecho', [50, 100, 200]],
  ['mariposa', 'Mariposa', [50, 100, 200]],
  ['combinado', 'Combinado', [100, 200, 400]],
];
export const MARCAS_INICIO = { seguidas: ['50-pecho', '100-pecho', '50-libre'], principal: '100-pecho', comp: ['50-pecho', '100-pecho', '50-libre'] };
